from enum import Enum

class Origin(Enum):
  BETA = 'BETA'
  BITAGAP = 'BITAGAP'
  BITECA = 'BITECA'

class Table(Enum):
  ANALYTIC = 'ANALYTIC'
  BIBLIOGRAPHY = 'BIBLIOGRAPHY'
  BIOGRAPHY = 'BIOGRAPHY'
  COPIES = 'COPIES'
  GEOGRAPHY = 'GEOGRAPHY'
  INSTITUTIONS = 'INSTITUTIONS'
  LIBRARY = 'LIBRARY'
  MS_ED = 'MS_ED'
  SUBJECT = 'SUBJECT'
  UNIFORM_TITLE = 'UNIFORM_TITLE'
