version: '3.4'

services:
  quickstatements:
    image: jmformenti/quickstatements:wmde.4
    restart: unless-stopped
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./data:/quickstatements/data
      - ./quickstatements.php:/var/www/html/quickstatements/public_html/quickstatements.php
    ports:
      - "${QUICKSTATEMENTS_PORT}:80"
    environment:
      - WIKIBASE_SCHEME_AND_HOST=https://pbuidev.wikibase.cloud
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://qs.philobiblon.duckdns.org:${QUICKSTATEMENTS_PORT}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=https://pbuidev.wikibase.cloud
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
      - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
      - OAUTH_CONSUMER_SECRET=${OAUTH_CONSUMER_SECRET}
